create table if not exists public.projetos (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  descricao text,
  created_at timestamptz not null default now()
);

create table if not exists public.protocolos (
  id bigint generated by default as identity primary key,
  projeto_id bigint not null references public.projetos(id) on delete restrict,
  numero_protocolo text not null,
  orgao text not null,
  responsavel text not null,
  link_consulta text,
  tipo_consulta text not null,
  status_atual text not null default 'Pendente',
  situacao text,
  observacao text,
  data_abertura date,
  data_finalizacao date,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (projeto_id, numero_protocolo, orgao, tipo_consulta)
);

create table if not exists public.historico_consultas (
  id bigint generated by default as identity primary key,
  protocolo_id bigint not null references public.protocolos(id) on delete cascade,
  status text,
  observacao text,
  data_movimentacao date,
  data_consulta timestamptz not null default now(),
  mudou_status boolean not null default false,
  erro text,
  fonte text,
  tipo_consulta text
);

alter table public.projetos enable row level security;
alter table public.protocolos enable row level security;
alter table public.historico_consultas enable row level security;
